# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks! # Add this if you are targeting iOS 8+ or using Swift
#platform :ios, '9.0'
pod 'AFNetworking', '~> 2.0'
pod 'CocoaAsyncSocket'  

target 'ScheduledHttpRequest' do

end

